### ISSUE TITLE
Sets, Logic, Computation An Open Logic Text PAGE 16

### ISSUE THREAD

**Issue by VictorHUGOcl** [OpenLogicProject/OpenLogic#100]
I think there is a mistake in first paragraph of page 16 in the text: Sets, Logic, Computation. 
But maybe I just didn't understand the definitions, I'm new on this topics so please let me know if I'm not right.
(besides my english is not very good, but I hope you can understand me)

The problem is that If (R' = R ∪ IdX) and ( R' = R \ IdX) are both the case then in follows that                               (R∪IdX= R \ IdX) and this last identity seems to me problematic it says that taking R and add it up Ixd is the same thing as taking R and substract from it Idx. Furthermore I think given the notation established in the first lines of this paragraph the most intuitive "formalization" of the following line: "Conversely, starting from a weak partial order, one can get astrict partial order by removing IdX"
is this R = R' \ IdX. So the mistake is in the last identity of this paragraph. Here is an extraction from the book of the mentiones paragraph:

CHAPTER 2. RELATIONS                                                                                                              16

"A strict partial order R on X can be turned into a weak partial
order R' by adding the identity relation on X : R' = R ∪ IdX .
Conversely, starting from a weak partial order, one can get a
strict partial order by removing IdX , i.e., R' = R \ IdX ."

**Comment by rzach** [comment]
You're right, that is confusing. The idea is that if R is a strict order, R' is weak; and if R is a weak order, R' is strict -- but the R' is a different relation in the two cases. I've cleared it up.

**Comment by rzach** [comment]
Thanks!
