### ISSUE TITLE
Sets, Logic, Computation An Open Logic Text: chapter 2

### ISSUE THREAD

**Issue by VictorHUGOcl** [OpenLogicProject/OpenLogic#101]
In Chapter 2 of Sets, Logic, Computation An Open Logic Text, you gave definition of the following:
Partial order.
linear order. 
Preorder.
Partial order.
strict partial order 
etc. 
But there isn't a definition of Weak partial (linear) order, why ? Is it not necessary?

**Comment by rzach** [comment]
You're right, that should be cleared up.

**Comment by VictorHUGOcl** [comment]
Thanks for your answer. =)
