### ISSUE TITLE
Need reference to parts and chapters

### ISSUE THREAD

**Issue by riaqn** [OpenLogicProject/OpenLogic#103]
Currently we only have reference to sections via `\olref[p][c][s]{sec}`.
Maybe we can have reference to parts and chapters.

**Comment by rzach** [comment]
Shouldn't be hard. Just need to add 3-letter IDs in olpart and olchapter and test for "part" o "chap" in older.

**Comment by riaqn** [comment]
I 'll do that ASAP. BTW, do the IDs have to be 3-letter? Sometimes I find it better to use \fileid{alpha} than say, \fileid{alp}.

**Comment by rzach** [comment]
Can now be done as of https://github.com/OpenLogicProject/OpenLogic/commit/b384700722d78a0e76ebe7b0bb343a934229083e but \chapter and \part commands still have to be changed to \olchapter and \olpart
