### ISSUE TITLE
Expand methods/induction for structural induction

### ISSUE THREAD

**Issue by rzach** [OpenLogicProject/OpenLogic#106]
In https://github.com/OpenLogicProject/OpenLogic/blob/master/content/methods/induction/structural-induction.tex we very briefly outline inductive definitions and structural induction. Should also include defining functions on inductively defined sets by induction, and here the need for the cases to be disjoint. Add another example and problems.

**Comment by nicolewyatt** [comment]
This is a low priority for me for Fall.

**Comment by rzach** [comment]
fixed in commit faa28a62e3f0916cb8d96fea99793f152c9a6bef
