### ISSUE TITLE
Enumerations from Z+ or N?

### ISSUE THREAD

**Issue by rzach** [OpenLogicProject/OpenLogic#107]
The section on enumerations https://github.com/OpenLogicProject/OpenLogic/blob/master/content/sets-functions-relations/size-of-sets/enumerability.tex is inconsistent between enumerations being functions from N or from Z+; it should be unified. It is also inconsistent between an enumeration being partial or total. This section should prove the equivalence of the informal and the formal definition (it does so now just for the formal definition using a partial function). The zig-zag method of enumeration probably needs its own section.

**Comment by rzach** [comment]
@nicolewyatt agrees, we should switch this to Z^+.

**Comment by rzach** [comment]
There is a more significant problem in that the formal definition of enumeration now uses a surjective function, but no such function exists if X is empty. The explanation assumes that f may be partial, but that conflicts with the official definition of function.

**Comment by nicolewyatt** [comment]
I'm don't think I'm following this. If X is empty, then any function from Z+ to X is trivially onto X, no?

**Comment by nicolewyatt** [comment]
Oh, I see, the problem is with making enumerations always total functions. But surely that is just a good reason to stick with allowing partial functions to count.

**Comment by rzach** [comment]
Yes, but we previously decided to make functions total (and call mappings that are partial but functional "partial functions")!

**Comment by nicolewyatt** [comment]
Did we? I have trouble keeping track to be honest. 

Option 1: revise the definition to say any partial onto function or total onto function counts. (If function means total function, is the total there redundant?) Add argument to the effect that where X is non-empty there is always an onto function.

Option 2: Give a two part definition of enumerability -- X is enumerable if either it is empty or ...

**Comment by nicolewyatt** [comment]
Option 2 is easier but perhaps less elegant.

**Comment by rzach** [comment]
Ok I've fixed this in commit 370cb024dfd8515d893088475f883a3d32b4eb31 -- where I've also tried to completely avoid formulating the diagonal arguments as indirect proofs (ie made them intuitionistically ok).

**Comment by nicolewyatt** [comment]
Line 36/49 still has natural numbers rather than positive integers. At line 82 how about "The last argument shows .." rather than "The last proof shows..", since part of the motivation is that the argument in question does not meet the standards of mathematical proof, no?

I have no views about the reformulated arguments, because intuitionists are crazy! ;)

**Comment by rzach** [comment]
They may be, but all I did was change the proof from the (confusing to students) "assume there is an enumeration of Pow(N) ....contradiction" to "lets show that every list of subsets of N must leave at least one set out".

**Comment by nicolewyatt** [comment]
You are no doubt right that is pedagogically better. I am pretty sure that is what I say to students in class in any case.
