### ISSUE TITLE
Pairing functions

### ISSUE THREAD

**Issue by rzach** [OpenLogicProject/OpenLogic#108]
We have an informal explanation of the pairing function in
https://github.com/OpenLogicProject/OpenLogic/blob/master/content/sets-functions-relations/size-of-sets/enumerability.tex
but it will be useful (and of interest) to have one or two explicit pairing functions. Add a section on that.

**Comment by marcusrossberg** [comment]
Might that fit in here?

[(https://github.com/OpenLogicProject/OpenLogic/blob/master/content/sets-functions-relations/sets/pairs-and-products.tex)]

I could have a go at that.  Are you thinking Weiner-Kuratowski and an arithmetical one?

**Comment by rzach** [comment]
I was thinking the arithmetical ones, ie how to compute the place in the zig-zag enumeration from the coordinates. But constructing ordered pairs is a good idea too. Should probably each be their own sections. (And maybe it's own issue?)

**Comment by marcusrossberg** [comment]
Oh, right.  Of course.  Sorry.
Yes, both would be good, I think.

**Comment by rzach** [comment]
Kuratowski pair: https://github.com/OpenLogicProject/OpenLogic/issues/134

**Comment by rzach** [comment]
Hey @marcusrossberg  are you still planning to do this?

**Comment by marcusrossberg** [comment]
I looked over the whole thing and I am no longer convinced we need this---esp. since it's briefly mentioned in

[https://github.com/OpenLogicProject/OpenLogic/blob/master/content/first-order-logic/models-theories/set-theory.tex]

Thoughts?

If there's a desire to add it, I'm happy to do it.

**Comment by rzach** [comment]
But the arithmetical pairing function(s) aren't... see https://github.com/OpenLogicProject/OpenLogic/issues/108#issuecomment-309286271

But if you weren't planning to write *that*, just the set theoretic definition of pairs, then no worries. I'll get to it at some point.

**Comment by marcusrossberg** [comment]
[#180](https://github.com/OpenLogicProject/OpenLogic/pull/180)

(I probably didn't do the pull request right again, but I'm sure you can sort it out, @rzach.)

**Comment by rzach** [comment]
Well, this has been fixed for a while. Thanks again though.
https://github.com/OpenLogicProject/OpenLogic/commit/ff202ca2f0eef79cf37c863177396b4e283075d4
