### ISSUE TITLE
What if TMs run off the tape?

### ISSUE THREAD

**Issue by rzach** [OpenLogicProject/OpenLogic#113]
The definition of a configuration of a TM yielding another in one step leaves out the case where the machine is scanning square 0 and wants to go left. What happens? Does it halt? Does it stay put but doesn't halt?

**Comment by rzach** [comment]
Ok, so Sipser doesn't actually mark the left end of the tape, only Papadimitriou does. And he handles that case by requiring that M never moves left when reading \TMendtape it doesn't move left. That's probably easiest.

**Comment by rzach** [comment]
I think the easiest is to have the machine halt if it runs off the tape. No extra conditions, minimal addition required for undecidability proof. Tape end symbol is not special so it'll be easier to eg prove that recursive functions are Turing computable.

**Comment by nicolewyatt** [comment]
Is this where I should grumble about it being better to stick with tape infinite in both directions? ;)

**Comment by rzach** [comment]
Only if you want to redo the undecidability proof!

**Comment by rzach** [comment]
Ok, I decided to just make the machine stay put. If we made it halt, we'd lose the result that we can always have a single designated halt state (or at least the easy proof of it).
