### ISSUE TITLE
Diagrams for sets & functions

### ISSUE THREAD

**Issue by rzach** [OpenLogicProject/OpenLogic#119]
sfr/sets/unons-and-intersections could use some Venn diagrams and sfr/functions/functions-basics diagrams for functions (esp injective, surjective)

**Comment by pdaniell** [comment]
I have some interest in perhaps completing this issue and then submitting a pull request. Did you have any requirements on what style (monochrome, color, what typeface, etc.)  the diagrams should be in and the file format? It seems all the injection/bijection/surjection diagrams on the internet are mostly of two ovals with arrows from the left oval to the right oval.

**Comment by rzach** [comment]
Thanks! It would be best to draw them in tikz in the source code itself rather than have separate image files. That will make it better to handle, esp. if you change the typeface or size.  Color is ok but b/w is fine too (probably better actually).  I'm thinking little circles for elements, curved arrows for the function.

**Comment by pdaniell** [comment]
Ok I can do it in TikZ, I was thinking about doing it in illustrator at first but you are probably right that managing the typeface will probably be hassle. What directory should I place the files in? Is assets the right location?

**Comment by rzach** [comment]
If you do it in TikZ you can do it in the files themselves, i.e., after the definition in https://github.com/OpenLogicProject/OpenLogic/blob/master/content/sets-functions-relations/functions/function-kinds.tex

**Comment by pdaniell** [comment]
Richard, I tried doing this in TikZ at first but it was ugly. 
What I wanted from this illustration was something more stylish and something that matched the the illustrative style of the portraits of the logicians. So I tried something in illustrator --- 

I am attaching my results for constant function, injection, surjection,  bijection. What do you think? I  feel like if they are plain ovals it will look boring. These look hand-drawn. The problem is that i have it as an AI file -- and they can be converted to SVG. Don't know about TIKZ.
![functions](https://user-images.githubusercontent.com/5911713/27601505-8a269554-5b67-11e7-864e-d6dbc4c93ac3.png)

**Comment by pdaniell** [comment]
I added the AI files etc at https://github.com/pdaniell/logic.open

**Comment by pdaniell** [comment]
I realize I forgot to add the set diagrams. I've added three more images of the same style
![functions_sets](https://user-images.githubusercontent.com/5911713/27637806-e714e86e-5c08-11e7-8e77-873fa4825911.png)

Also in my own repo I changed the location of the images -- I put them here in assets/diagrams

https://github.com/pdaniell/logic.open/tree/master/assets/diagrams

One thing I realize is that I can actually save AI files as EPS files. Maybe that's an alternative? There are tools out there to convert SVG files into TikZ 

https://github.com/paaguti/svg2tikz

but at this point I wonder whether there is any advantage in storing it in markup when the generated markup will probably not be human editable.

**Comment by rzach** [comment]
These are wonderful, love the hand-drawn feel.

I tried out the svg2tikz conversion thing and it worked great except it lost the dots. But I can work with that.  (The reason I'd like to provide them as tikz images is that it's a lot easier to change colors, line styles, and typeface of labels to match the text -- eg, the red may clash with other colors in the text, and you don't want to have to go back to the source .ai and change all the line colors and save as new images.)

Two requests:
1. Can we have another dot + arrow or two for the bijective function?
2. The last diagram is the symmetric difference, which we haven't defined -- remove shading on the right, then it's a diagram for X \setminus Y.

If you feel enterprising, it would be wonderful to have a diagram for composition of functions.

**Comment by pdaniell** [comment]
Ok I have checked in another copy in my fork with one more dot in the bijection (two made it busy and also all the other diagrams have three arrows). I added setminus (I didn't get rid of sym diff ). 

![functions_sets](https://user-images.githubusercontent.com/5911713/27644623-f3f8189a-5c1b-11e7-8e37-9448ed599f74.png)

I can think about how to do composition --- did you have something in mind for that? I suppose you could have three circles with two sets of arrows -- and then a set of dotted arrows indicating the composition

**Comment by rzach** [comment]
Yes, that's what I was thinking too (re: composition).  Maybe make the first f surjective but not injective and the second injective but not surjective; then we can illustrate that composition of injective functions is injective and of surjective functions is surjective just by removing dots and arrows.

**Comment by pdaniell** [comment]
Ok I've added it in a separate file called "composition"
 
![composition](https://user-images.githubusercontent.com/5911713/27656615-8699ceda-5c41-11e7-939e-8cf64c4bcf4f.png)

If i used the hand-drawn lines for all the arrows, it looked a little messy. So I used the pen tool to create the arrow for the composition lines. 

The hex color of the the red is: A91E22
The hex color of the gray is: A7A9AC
The hex color of the blue is: 1B75BC

**Comment by rzach** [comment]
Update:

- I experimented both with the svg2tikz utility you linked and with the Inkscape tikz export extension https://github.com/kjellmf/svg2tikz Both work reasonably well but the extension seems to be more reliable (the other utility sometimes produces no output and I couldn't figure out what makes it do that)

- The Tikz code isn't pretty but the output looks good.  I've been fighting with two issues for putting it into the text:

-- Color: to make sure the colors work with whatever colors the text uses, they have to be redefinable. The Inkscape extension defines color names based on the RGB hex code, so it's pretty easy to redefine colors or to switch those color names for color names set by open-logic-config.sty

-- Scaling: that's the harder issue.  The `tikzscale` package lets you import tikz pictures via `\includegraphics`, which obeys the width= parameter. The problem is that although it scales the paths it doesn't scale the line widths. But in any case the line widths are probably also something the style should be able to set.  But depending on how you import the .ai into Inkscape and then also depending on whether the Tikz code will have the line widths in different units and at different scaling factors, so a simple s/width=6pt/\arrowidth/g doesn't work reliably.

My plan is to find a way to include tikz images and scale them with the line widths. That's probably pretty easy since you can just scale the box produced by tikz and that should scale everything including widths. 

I'm thinking we should have a separate repository for diagrams in editable format with all the conversion tools. Maybe AI, SVG for Inkscape, the Tikz produced by Inkscape export, and the scripts process the Tikz and put them into the main repo at assets/diagrams?

**Comment by rzach** [comment]
We have diagrams; new issue for a) documenting how we got them and b) making them show up in the text better.
