### ISSUE TITLE
Summaries Are Missing From Source

### ISSUE THREAD

**Issue by Buddybenj** [OpenLogicProject/OpenLogic#121]
The summaries for each chapter aren't in the repository, yet they are in the PDF available on the website.

**Comment by rzach** [comment]
I assume you mean the chapter summaries in "Sets, Logic, Computation"?  They are in https://github.com/rzach/phil379 (see the include directory).

**Comment by Buddybenj** [comment]
Ah, thanks for letting me now. Sorry for the mistake.
