### ISSUE TITLE
0 or zero

### ISSUE THREAD

**Issue by rzach** [OpenLogicProject/OpenLogic#123]
Primitive recursive functions: do they start with the "constant" zero, or the one-place function that's constant =0?  Currently: the former. Benefit of latter: zero(x) is actually a function and we don't have to worry about/explain 0-place functions being functions.

**Comment by SaraUckelman** [comment]
I find it more harmonious to start with three functions -- zero, successor, and projection -- rather than muddy the waters by introducing constants.

**Comment by rzach** [comment]
Persuaded!
