### ISSUE TITLE
Turing Machine simulator recommendation

### ISSUE THREAD

**Issue by rzach** [OpenLogicProject/OpenLogic#126]
The chapter on Turing machines should have (a) recommendation(s) for free, web-based TM simulators that people can easily use with the way we've set up the definition of TMs to run examples from the book/text out problems.

What are good ones? 

Bonus points for open source things that we can potentially adapt and put on the openlogicproject.org site.

**Comment by blopesvieira** [comment]
JFlap is very nice and have many interesting functions.

jflap.org

Em ter, 23 de mai de 2017 15:50, Richard Zach <notifications@github.com>
escreveu:

**Comment by rzach** [comment]
This is cool but perhaps a bit too involved & complex. Was thinking of something that doesn't require a download, install, and reading a manual.

Thus far we recommended 

http://morphett.info/turing/turing.html (this one's open source: https://github.com/awmorp/jsturing)
https://turingmachinesimulator.com/

There's also a finite state diagram drawing program
http://madebyevan.com/fsm/

**Comment by rzach** [comment]
slc.openlogicproject.org now recommends turing.openlogicproject.org in the preface
