### ISSUE TITLE
Kuratowski Pair Construction

### ISSUE THREAD

**Issue by rzach** [OpenLogicProject/OpenLogic#134]
We introduce ordered pairs as primitive, but it would be useful to discuss the Kuratowski definition of ordered pairs intuitively. It is mentioned (but very quickly only) in 

https://github.com/OpenLogicProject/OpenLogic/blob/master/content/first-order-logic/models-theories/set-theory.tex

Add a section to https://github.com/OpenLogicProject/OpenLogic/tree/master/content/sets-functions-relations/sets to discuss it and explain how it works.

**Comment by marcusrossberg** [comment]
May I also suggest a recursive definition of n-tuple, while we're at it?
Also see here: #136, for a further issue in that section.
