### ISSUE TITLE
Soundness theorem for Natural Deduction

### ISSUE THREAD

**Issue by marcusrossberg** [OpenLogicProject/OpenLogic#135]
In the proof of the soundness theorem for natural deduction here:

https://github.com/OpenLogicProject/OpenLogic/blob/master/content/first-order-logic/natural-deduction/soundness.tex

the clause for \lif intro strikes me as unnecessarily complicated.  It follows straightforwardly from the Semantic Deduction Theorem — last theorem here: 

https://github.com/OpenLogicProject/OpenLogic/blob/master/content/first-order-logic/syntax-and-semantics/semantic-notions.tex

(\ollabel{thm:sem-deduction}) — or am missing a pedagogical (or other) point?

I any case, the sentence in the middle, 

     "We need to show that, if $\Gamma \Entails !A \lif !B$." 

has at least a superfluous "if", but I guess, to be uniform with the other cases, that should really be 

     "We need to show that, if $\Sat{M}{\Gamma}$, then $\Sat{M}{!A \lif !B}$."

Which way to go?  Simplify with reference to thm:sem-deduction or just correct the sentence above?

**Comment by rzach** [comment]
I think I meant to keep it self-contained. Also, since the IH gives you two different sets of open assumptions, the semantic deduction theorem doesn't apply directly.  Anyway, it is fixed.
