### ISSUE TITLE
Use standard natural deduction rules and names

### ISSUE THREAD

**Issue by rzach** [OpenLogicProject/OpenLogic#144]
The natural deduction chapter uses nonstandard rules. Replace them by Prawitz rules, ie intuitionisim and classical absurdity rules, A, -A |- \lfalse is -Elim not \lfalse Intro.

**Comment by rzach** [comment]
@nicolewyatt do you want this for Fall (or at all)?

**Comment by nicolewyatt** [comment]
I always do sequent calculus in 379 so not needed for me ever.
