### ISSUE TITLE
Use standard sequent calculus with sequents

### ISSUE THREAD

**Issue by rzach** [OpenLogicProject/OpenLogic#145]
The sequent calculus is presented with sequents being sets of formulas. Switch to sequences so it is more standard and allows future expansion by discussion of substructural logics.

**Comment by nicolewyatt** [comment]
How time consuming will this fix be? I would like this for the Fall but I realize time is getting short.

**Comment by rzach** [comment]
Should be doable; the harder part will be to fix arithmetization of syntax for LK, but you don't need that.
