### ISSUE TITLE
Docker container for Travis CI

### ISSUE THREAD

**Issue by rzach** [OpenLogicProject/OpenLogic#149]
We have a basic Travis CI setup for testing, but a Docker container would be better/more efficient.

Also, describe how it's done for the website?

**Comment by emanuelbuholzer** [comment]
Do you mean with "how it's done for the website?", the hosting of the site including the place for generated PDFs, etc. or do you want to build the website in Docker too?

**Comment by rzach** [comment]
No just document the process and post it on the website...

**Comment by emanuelbuholzer** [comment]
With a few additional changes the Dockerfile, the Docker container could also be used for compiling OLT, as described here: https://github.com/OpenLogicProject/OpenLogic/wiki/Compiling-OLT.

This would allow contributors not having LaTeX installed on their machine and may reduce some content in the wiki about compiling it.

**Comment by rzach** [comment]
Markdown is great; I can run it through pandoc to get HTML for a website post

**Comment by emanuelbuholzer** [comment]
Great! Would you like to have the post about how the Dockerfile works etc. or only how it can be used to test if everything still runs locally?

**Comment by rzach** [comment]
I'm not sure what "how it can be used to test if everything still runs locally" means but why not both?

BTW unless its super easy to do I don't think it's worth your time to figure out how to let people compile without having LaTeX installed. I think the number of people who that would apply to is very small, if not zero. (Also, you can just put everything on Overleaf and compile there if you really don't wnat to install it locally.)

**Comment by emanuelbuholzer** [comment]
Haha sounds good! I meant to with it, that someone can test if the build works locally. Thanks for the feedback! 😃

**Comment by rzach** [comment]
The CI is now broken because I need another LaTeX package (prooftrees) which isn't in the Debian packages currently being loaded. Easy fix?

**Comment by pdaniell** [comment]
Per this page https://packages.debian.org/stretch/texlive-science
it looks like prooftrees is in the package texlive-science. 

So you might be able to add ```texlive-science \``` to line 16 of the Dockerfile. Though it will add more packages than just prooftrees. (Remember to add the trailing backslash or the following lines will mess up in the docker build.)

**Comment by rzach** [comment]
To avoid loading the entire package can we just add

`ADD http://mirrors.ctan.org/graphics/pgf/contrib/prooftrees/prooftrees.sty prooftrees.sty`

like we did for `gitinf2`?

**Comment by emanuelbuholzer** [comment]
Looks good to me. You can probably test this locally in the repository using:
```
docker build -t prooftrees .
docker run -v `pwd`:/wd prooftrees make
```

**Comment by rzach** [comment]
Hm. Problem is that prooftrees needs a newer version of forest.sty than what's in the trusty or xenial release of texlive, and the xenial backport of texlive packages doesn't include texlive-pictures, which is where forest.sty lives. CTAN's https://ctan.org/tex-archive/graphics/pgf/contrib/forest only includes forest.dtx but not forest.sty 

https://github.com/OpenLogicProject/OpenLogic/pull/166/files

Ideas?

**Comment by rzach** [comment]
Never mind, found it https://github.com/OpenLogicProject/OpenLogic/commit/e5402bee7f84c3e72b937b48356efb68e0a7597a

**Comment by rzach** [comment]
@emanuelbuholzer do you still want to do that blog post on how to set up CI for LaTeX projects? If you don't have time, no prob. Then I'd just close this since it's working now.

**Comment by emanuelbuholzer** [comment]
@rzach I have it on the radar but haven't found a nice structure, content and time yet. The main benefit I see is that you can reproduce your CI builds locally. Can you think of anything else that I'm missing? I'll give it a try this week or next week, so we can discuss if it is valuable or not.

**Comment by rzach** [comment]
This is now super easy with Github Actions see #285.
