### ISSUE TITLE
Isn't Identity relation antisymmetric?

### ISSUE THREAD

**Issue by vinothkr** [OpenLogicProject/OpenLogic#152]
https://github.com/OpenLogicProject/OpenLogic/blob/5593a32c9466f72d0c2d92879468b7ca73e69b54/content/sets-functions-relations/relations/orders.tex#L42

In the previous paragraph, its mentioned that Identity is both symmetric and anti-symmetric. Here its mentioned that identity isn't.

**Comment by rzach** [comment]
You're perfectly right. Fixed, thanks! 29c268a6fdd362a9df09e2c153e2ecb7f1b7ccd1
