### ISSUE TITLE
Errata in unions and intersection

### ISSUE THREAD

**Issue by vinothkr** [OpenLogicProject/OpenLogic#153]
https://github.com/OpenLogicProject/OpenLogic/blob/29c268a6fdd362a9df09e2c153e2ecb7f1b7ccd1/content/sets-functions-relations/sets/unions-and-intersections.tex#L20

That line should either read as "a name and a symbol" or "a name and define a symbol" right?
Like this
https://github.com/OpenLogicProject/OpenLogic/compare/master...vinothkr:master

**Comment by rzach** [comment]
Thanks; you can send a pull request directlyif you have it changed in your fork
