### ISSUE TITLE
Proof of Monotony refers to Compactness

### ISSUE THREAD

**Issue by vinothkr** [OpenLogicProject/OpenLogic#155]
The Proposition 8.14 of Sequent Calculus, refers to Proposition 8.17 It would be nice if we either refer to that or introduce Monotony after compactness.
It was kind of sudden when it talks about finite subsets of the Sigma.

**Comment by rzach** [comment]
I'm not sure why you think Pop 8.14 refers to proposition 8.17. It just refers to Def 8.11 -- but maybe we should make that explicit.

**Comment by rzach** [comment]
Amend https://github.com/OpenLogicProject/OpenLogic/blob/89c647423489cf2ac3c4e23b546b7be6a85e4a5c/content/first-order-logic/sequent-calculus/proof-theoretic-notions.tex#L92 to refer to definition of \Proves to make clear that \Proves is trivially compact and this does not need Compactness.

**Comment by rzach** [comment]
Fixed in commit 0cda459
