### ISSUE TITLE
Your access to this site has been limited

### ISSUE THREAD

**Issue by alex-bender** [OpenLogicProject/OpenLogic#182]
Hello.
I would like to get the recent versions of compiled book,
but I can't access website, probably because of my location.
That's really sad to realize that even nowadays location of
the person is predominant in judging rather access should be gained or not.
So is there another way to get white-listed?
Thanks.
Your projects it excellent.

**Comment by rzach** [comment]
I don't think the website is blocking access. Perhaps it's your ISP who is? Can you get to the site via a VPN or Tor?

**Comment by rzach** [comment]
By the way openlogicproject.og and builds.openlogicproject.org are on two different servers. Which one do you have trouble with? (PDFs are on the latter.)

**Comment by alex-bender** [comment]
I don't think that it is ISP, because I can't reach (the first) site from different networks (and internet providers)
Here is what I see:
![image](https://user-images.githubusercontent.com/3628862/45115657-2d98e280-b159-11e8-9c9d-d6d73d93641e.png)
The second one is actually accessible, didn't know that PDFs are there.
Thanks for pointing.

**Comment by jpellegrini** [comment]
Wordfence a Wordpress plugin. Whoever is hosting Wordpress may be able to adjust its configuration.

(I am also blocked -- I'm from Brazil)

**Comment by rzach** [comment]
@jpellegrini I'm trying to fix it but ftr the PDFs are on http://builds.openlogicproject.org/ which is not region-blocked.

**Comment by rzach** [comment]
Is it working now? https://openlogicproject.org/

**Comment by jpellegrini** [comment]
> Is it working now? https://openlogicproject.org/

Yes!!! Thank you so much!

**Comment by alex-bender** [comment]
Thanks! Closing that now.
