### ISSUE TITLE
Boxes and Diamonds: Another issue in simultaneous substitution section 1.3

### ISSUE THREAD

**Issue by pbm** [OpenLogicProject/OpenLogic#186]
The Boxes and Diamonds book seems to follow a different plan than the open-logic-complete book (comparing section 38.3 of open-logic-complete with section 1.3 of Boxes and Diamonds book.

### Numbers 5, 6, 7, and 8 of definition 1.3 suffer one more problem:

after the `:` they all substitute into the generic `A` formula ( `A[D_1/p_1...] is ...`) rather
than the full formula being demonstrated e.g. `(B and C)[D_1/p_1,...] is...`

So either make the following change
```
    5: A equiv (B AND C):  A[D_1/p_1,...] is (B[D_1/p_1,...]) AND C[D_1/p_1,...])
```
To
```
    5: A equiv (B AND C):  (B AND C)[D_1/p_1,...] is (B[D_1/p_1,...]) OR C[D_1/p_1,...])
```
or switch to the form in the open-logic-complete book (see below).
Same with 6,7, and 8.    

### Numbers 4, 9, and 10:  It looks like nothing is going on

E.g.,  number 4:
```
... not B[D_1/p_1...] is NOT B[D_1/p_1...]
```
Would parenthesis help illustrate what is going on?  
```
  (not B)[D_1/p_1...] is NOT (B[D_1/p_1...]) ?
```

Alternatively, you could go with the form from the open-logic-complete.pdf 38.3 (which seems to be different than the Boxes and Diamonds book), where all the substitutions are of the form:
```
phi[theta_1/p_1,...] is NOT psi[theta_1/p_1...]
```

**Comment by rzach** [comment]
Fixed with commit  145ae4a; thanks for reading so closely!
