### ISSUE TITLE
Typos in Theorem 5.4

### ISSUE THREAD

**Issue by pbm** [OpenLogicProject/OpenLogic#187]
Looks like several typos in theorem 5.4

> Theorem 5.4. Principle of induction on formulas: If some property P holds of all
the atomic formulas and is such that
> 1. it holds for ¬φ whenever it holds for φ;
> 2. if holds for and (φ ∧ ψ) whenever it holds for φ and ψ; 
> 3. if holds for and (φ ∨ ψ) whenever it holds for φ and ψ; 
> 4. if holds for and (φ → ψ) whenever it holds for φ and ψ;
> then P holds of all formulas.

In 1, are you missing a "does not".  Should it be "1. it holds for  ¬φ whenever it DOES NOT hold for φ"?

In 2, 3, and 4, should the initial "if" be "it"?

In 3  should the "and" be "or":  "...it holds for φ OR ψ;"

In 4 should the final clause needs to be rewritten to something like "...whenever it holds for ψ or does not hold for φ"?

**Comment by rzach** [comment]
Yes to "it" for "if"

But the rest is right: this is just the principle of induction: if something holds for all atomic formulas and is preserved when passing to more complex formulas, it's true for all formulas. Eg you use this to prove that all formulas have the same number of left and right parentheses; that wouldn't work if your inductive step had to use "~φ has the same number of left and right parentheses if φ does NOT have the same number of left and right parentheses".

Thanks!
