### ISSUE TITLE
Concatenation of TMs

### ISSUE THREAD

**Issue by rzach** [OpenLogicProject/OpenLogic#191]
The discussion of the Halting Problem assumes we can run one TM after another: this requires showing that we can assume a TM halts on the 1st square whenever it halts. This is also needed to show that recursive functions are Turing computable. We should discuss this.

**Comment by nicolewyatt** [comment]
I do this in class, albeit in a relatively hand wavy way.  I suppose we could just define TMs in such a way that halting requires stopping on the first square. (in which case I would still do the handwavy thing in class, just to show that if they cease operation at all there is a related machine that halts properly speaking.) Or we could add to the Halting Problem set up an interim machine that puts the whole thing back in SIC. And then have building such a machine as an exercise.

**Comment by rzach** [comment]
@feffemannen in pull request #259 pointed out another problem: the definition of "output" allows the output to start anywhere on the tape. That means when we concatenate TMs, the second TM, even if it starts on the first square, can't tell if the input is blank or not.
I propose the following:
- Change the definition of "output" of a TM to be the the largest string S ending in a non-blank symbol such that the tape in the halting configuration is > + S + blank^\omega (ie output starts on square 1). This is in line with most other textbooks I think.
- Add an example to the section on unary representation of numbers, namely a doubler machine which leaves its output at the beginning of the tape.
- Expand the section on halting states to one on "well-behaved" TMs, which have a halting state and halt with the tape head always on square 1. Perhaps also require that they never erase the tape start symbol or try to move left of it.  (Open to suggestions on the terminology.)  Example: adder machine + state that makes it go back to beginning + dedicated halt state.
- Revise section on composition of TMs to require that the first TM is well behaved.
- Expand the section on variants to start with examples we've already seen: If a function is computable, it is computable by a TM with a dedicated halting state. If a function is computable, it is computable by a TM which halts with the tape head on square 1. Describe the variants in a bit more detail and add exercises asking students to think about/explain why the variants don't add any computing power.

**Comment by rzach** [comment]
@nicolewyatt do you have an opinion? I'll start TMs in 2 weeks and if I have time I might do it the new way/make those changes

**Comment by nicolewyatt** [comment]
This is effectively what I have done in the past anyway -- that is, my discussion of what I used to call (following BFC whom I learnt it from) standard initial and standard final configuration puts constraints on both how the machine ends and where the output is, and I have had students expand a machine to put things in the right place, as it were. I don't have any objecting to defining the machines that way. So Yes?
