### ISSUE TITLE
Website blocks access from Russia

### ISSUE THREAD

**Issue by laserbat** [OpenLogicProject/OpenLogic#193]
When I try to access http://openlogicproject.org/ I get the following message from wordfence

> Your access to this site has been limited
> Your access to this service has been temporarily limited. Please try again in a few minutes. (HTTP response code 503)
> Reason: Access from your area has been temporarily limited for security reasons.

The website works fine when I'm accessing it from a non-Russian IP.

**Comment by iblech** [comment]
I get a similar (though not the same) message when trying to access the website via Tor.

**Comment by rzach** [comment]
Unfortunately, I don't run the server and can't fix this. The server has had a lot of trouble with spam attacks from Russia, so their solution was to region-restrict access.

Until I can move the site to a different server, you can access the PDFs at http://builds.openlogicproject.org/  That should not be region-restricted.

**Comment by rzach** [comment]
Unfortunately, I don't run the server and can't fix this. The server has had a lot of trouble with spam attacks from Russia, so their solution was to region-restrict access.

Until I can move the site to a different server, you can access the PDFs at http://builds.openlogicproject.org/  That should not be region-restricted.

**Comment by laserbat** [comment]
Thank you for this information!

**Comment by rzach** [comment]
Moved servers! Is it working? https://openlogicproject.org/
