### ISSUE TITLE
Sentence initial token for formula(s) doesn't exist

### ISSUE THREAD

**Issue by nicolewyatt** [OpenLogicProject/OpenLogic#20]
The documentation for the config file suggests that !P{token} should give you a capitalized plural version of the token and !S{token} a capitalized singular version. This doesn't seem to work for formula. I didn't check for the other tokens. Is it implemented yet?

**Comment by nicolewyatt** [comment]
!p{formula} doesn't work either.

**Comment by rzach** [comment]
I changed it the other day, see https://github.com/OpenLogicProject/OpenLogic/wiki/Tokenized-Text

Documentation in open-logic-config.sty fixed with commit #3d58343
