### ISSUE TITLE
Different versions of axiom Q8, and lemmas 31.22-23

### ISSUE THREAD

**Issue by frabjous** [OpenLogicProject/OpenLogic#200]
In chapter 29 (931aeb0 debug version page 415), Q8 of system Q (Robinson arithmetic) is listed as:

(Q8-A) ∀x∀y(x < y ↔ ∃z(x+z' = y))

But in chapter 32, same version page 440

(Q8-B) ∀x∀y(x < y ↔ ∃z(z'+x) = y)

The difference seems trivial, I know,  but since Robinson arithmetic does not have a general commutativity of addition principle, it affects proofs. 

In particular, I'm confused about Lemmas 31.22 and 31.23 on page 452. For part 2 of 31.22, only the base step of the induction is included in the text, and I cannot for the life of me figure out how to get the induction step to work using (Q8-B). I *can* get it work with (Q8-A), but if I use (Q8-A), the proof given for 31.23 does not work, and I cannot figure out how to recover it, at least not in weak Q. (In PA, it's not a problem.)

For the project, I'd suggest making the two definitions consistent, and then either filling out the proof of 31.22 so it's complete or revising the proof of 31.23, and indeed, I'd be very grateful if someone could point me towards an alternative text that actually carries out these proofs, as at the moment, I have to admit defeat. (All the textbooks I've looked at either use a different axiomatization of Q, or leave them as an exercise!)

[EDIT: After a brief rest, I figured out the induction step for 31.22 using Q8-B, though it's far from trivial and I still think it should be added. I'm still completely in the dark of how one would get these lemmas using Q8-A, if it's even possible. I haven't had a chance to familiarize myself with your TeX files; when I get a chance, maybe I'll do a pull request.]

**Comment by rzach** [comment]
Thanks for this! I fixed the typo in ch 29 and will add a sketch of the induction step for Lemma 31.22(2).

Jeremy Avigad's notes follow Epstein & Carnielli, _Computability_. The lemma in question is Lemma 15 on p. 195 of that book, with a proof on the following page.

**Comment by rzach** [comment]
Ok, I think I fixed it. I split proposition 22 into two. The relevant changes are on p. 12 & 13.

In the process, I found a much simpler proof. Proposition 21 is no longer required and can be deleted. Can you have a look?
[representability-in-q.pdf](https://github.com/OpenLogicProject/OpenLogic/files/3720995/representability-in-q.pdf)
(I also changed Q3 to a disjunction to make it work intuitionistically.)

**Comment by frabjous** [comment]
Thanks again. The proof of req.23, or (what is now) 33.23 looks good to me now. I gave a longer proof of the biconditional version [in my lecture notes](http://people.umass.edu/klement/513/ln.pdf), page 43, but for this direction it accords I believe.

There are some minor changes elsewhere that are needed. Referring to the latest clean version of the whole text, the wrong version of Q₈ is still given in Problems 24.3 and 24.4. And even more minor, the 8 in "Q8" is not subscripted where it appears near the end of section 24.4.
