### ISSUE TITLE
Better factorial

### ISSUE THREAD

**Issue by rzach** [OpenLogicProject/OpenLogic#215]
Since ! is active in math mode, it's not available for the factorial. The `\fac` in `sty/open-logic-formulas.sty` command provides a poor substitute. There should be a way to make `\fac` behave like ordinary ! in math mode and still have ! available for `!A` in math.

**Comment by bafain** [comment]
It's also not available for unique existential quantification. Here a thin space is rendered instead of the intended `∃!`:

https://github.com/OpenLogicProject/OpenLogic/blob/482c320128c3b8c44284a9a7cd7565932c8b60f6/content/first-order-logic/beyond/second-order-logic.tex#L171

**Comment by rzach** [comment]
That's because \! is actually a negative thin space. But: \lexists![x] already makes an "exactly one" quantifier.
