### ISSUE TITLE
Missing negation in the definition of modal logic

### ISSUE THREAD

**Issue by Kraks** [OpenLogicProject/OpenLogic#224]
Hi all, thanks for writing this great textbook!  I was recently reading the modal logic part, and found there might be a small mistake (in https://github.com/OpenLogicProject/OpenLogic/blob/master/content/normal-modal-logic/syntax-and-semantics/language-modal-logic.tex) 

The definition of modal logic includes negations, however, in the inductive definition of well-formed formulas, the negation is not mentioned anymore. If it indeed should be there, I'm happy to submit a follow-up pull request.

**Comment by rzach** [comment]
Thanks!
