### ISSUE TITLE
Irreflexivity and asymmetry defined confusingly  

### ISSUE THREAD

**Issue by kirk86** [OpenLogicProject/OpenLogic#226]
I was wondering why are `irreflexivity` and `assymetry` defined as subsets on `A` and not `A^2`. If `irreflexivity` is to be understood as the opposite of `reflexivity` shouldn't it be on `A^2`?

![relations](https://user-images.githubusercontent.com/2902390/72535462-7ba31780-3870-11ea-9cdd-219aee91673f.jpg)

**Comment by rzach** [comment]
"R is a relation on A" and "R \subseteq A^2" mean the same. But you're right, probably the statements should uniformly use one or the other terminology.

**Comment by kirk86** [comment]
I understand that `R` is a relation in both instances but visually I interpret `A^2` as a cartesian product made of ordered pairs, but how would I visualise `A`, in this instance, is it just the number line? (e.g. only x and not y)?
