### ISSUE TITLE
Nonstandard model 𝑲 of 𝐐

### ISSUE THREAD

**Issue by ionathanch** [OpenLogicProject/OpenLogic#233]
In the example structure **_K_** in Models of **Q**, × is interpreted as xy if x, y ∈ ℕ and _a_ otherwise. This doesn't seem to satisfy axiom Q6 (∀x (x × 0) = 0), since _a_ ⊗ 0 = _a_ ≠ 0. Maybe the interpretation should be changed so that x ⊗ y = xy if x, y ∈ ℕ, 0 if y = 0, and _a_ otherwise? (As far as I can tell, axiom Q7 is satisfied for either of these interpretations.)

**Comment by ionathanch** [comment]
I think I have a similar question for the structure **_K'_** in Computable Models of Arithmetic. It interprets the constant symbol _0_ as **z** = 1 and the function symbol + as +[**_K'_**](x, y) = x + y if x, y > 0 and 0 otherwise. From axiom Q4 (∀x (x + _0_) = x), we can get the formula _0_ + _0_ = _0_. Then **_K'_** ⊧ _0_ + _0_ = _0_ if +[**_K'_**](**z**, **z**) = **z**. But this is +[**_K'_**](1, 1) = 1, which is 2 = 1. Am I understanding all of these incorrectly, or maybe the models **_K_**, **_K'_** need to be adjusted to satisfy the axioms? (The same problem probably arises for axiom Q6 as well.)

**Comment by rzach** [comment]
Right, in K' + and × have to be changed to +(x,y) = (x-1)+(y-1) + 1 = x+y-1 and ×(x,y) = (x-1)(y-1)+1 = xy-x-y+2. You're probably right on K as well. I'll check when I get to my books later.
