### ISSUE TITLE
Typo in the section on Non-Enumerability

### ISSUE THREAD

**Issue by cel7t** [OpenLogicProject/OpenLogic#239]
Typo location: https://www.github.com/OpenLogicProject/OpenLogic/tree/master/content%2Fsets-functions-relations%2Fsize-of-sets%2Fnon-enumerability.tex
Line 90-91

What is the typo: "...changing every 1 to a 0 and every 1 to a 0. "

Proposed correction: "...changing every 1 to a 0 and every 0 to a 1."

**Comment by rzach** [comment]
Thanks, sorry this took so long!
