### ISSUE TITLE
one row too much in proof of 65.2

### ISSUE THREAD

**Issue by fredbok** [OpenLogicProject/OpenLogic#240]
Typo location:
https://github.com/OpenLogicProject/OpenLogic/blob/534a139ade186ee72e249fd0db465600b6e9fd01/content/methods/induction/induction-on-N.tex#L125

What is the typo:
The line contains n(k+1), mixing n and k

Proposed correction:
change n to k, i.e.
    & = \frac{k(k+1) + 2(k+1)}{2} = {}\\

**Comment by rzach** [comment]
Thanks!
