### ISSUE TITLE
Typo in "open_book_computability", section 2.3

### ISSUE THREAD

**Issue by anbncn** [OpenLogicProject/OpenLogic#242]
Typo location: In the first line of section 2.3 Composition (in F19, open_book_computability.pdf)

What is the typo: g(f(x)) missing last ")"

Proposed correction: Add missing ")"

**Comment by rzach** [comment]
Hi, I don't have this book, so I can't tell where this is. Do you have a link?

It's possible it's already fixed and this comes from an old version. I'm guessing it's this section:
http://builds.openlogicproject.org/content/sets-functions-relations/functions/composition.pdf
but that typo isn't in it (anymore).

**Comment by rzach** [comment]
Going to assume this is fixed, please reopen if not.
