### ISSUE TITLE
Typo in Primitive Recursive Notations?

### ISSUE THREAD

**Issue by s-truax** [OpenLogicProject/OpenLogic#246]
The most convenient way to report a typo should reference the file and line number where the typo occurs:

- Find the file in the content tree: https://github.com/OpenLogicProject/OpenLogic/tree/master/content
- Click on the line number; then on the menu indicated by three horizontal dots
- Select "Copy permalink" and paste that link below.

Alternatively describe the location of the typo (page #, "after Theorem 5.1", etc., and *mention which PDF you are referencing*)

Typo location: [Line 23](https://github.com/OpenLogicProject/OpenLogic/blob/09beb1ba32471d5c64615b0299ceab6882e1b4d4/content/computability/recursive-functions/notation-pr-functions.tex#L23) in `notation-pr-functions.tex`

What is the typo: The line states that a primitive recursive function notated as `$\fn{Rec}_k[G,H]$` will have an arity of `k + 1`, but then in [line 26](https://github.com/OpenLogicProject/OpenLogic/blob/09beb1ba32471d5c64615b0299ceab6882e1b4d4/content/computability/recursive-functions/notation-pr-functions.tex#L26) the primitive recursive function `add` is defined using this notation with `k == 2`. This seems to suggest the arity of `add` is `3`, when `add` is defined earlier with an arity of `2`.

Proposed correction: If this is a typo, then either line 26 should be `\fn{Rec}_1[\Proj{1}{0},\fn{Comp}_{1,3}[\Succ,\Proj{3}{2}]].` or line 23 should say that `$\fn{Rec}_k[G,H]$` will have an arity of `k`.

**Comment by rzach** [comment]
Thanks again!
