### ISSUE TITLE
Inverse functions

### ISSUE THREAD

**Issue by rzach** [OpenLogicProject/OpenLogic#262]
It'll be easier to define left and right inverses of functions. Then one can state & perhaps prove that the left inverse exists for injective, and the right for surjective functions. It then follows that bijective functions have both left and right inverses. Prove that for bijective functions these are unique, so bijective functions have a unique inverse.

**Comment by rzach** [comment]
Specifically, currently in http://builds.openlogicproject.org/content/sets-functions-relations/functions/inverses.pdf we just define what an inverse is and then show that if f is bijective it has one.  I think it would pedagogically make sense to do it as follows:

1. Define a left inverse as a g st g(f(x)) = x and prove that if f is injective it has a left inverse.
2. Define a right inverse as an h st f(h(y)) = y and prove that if f is surjective it has a right inverse.
3. Define an inverse as a function that is both left and right inverse. Keep the current discussion as a proof that if f is bijective it has an inverse.
4. Add as possible problems: 

  - show that if g is a left inverse of f and h a right inverse, then g = h. 
  - use this to show that if f has both left and right inverses it has a unique inverse
  - show that if f has a left inverse it is injective
  - show that if f has a right inverse it is surjective

Any objections @timbutton ?

**Comment by timbutton** [comment]
Hi Richard

Nice thought! It's certainly pedagogically useful: it's an important
category-theoretic idea, and it's a nice thing for students to get their
heads around.

That said, I'm not sure it's needed elsewhere in any of the builds? In
which case, I worry it's non-trivially more abstract than necessary?

Also, doesn't the proof of 2 need Choice?!

So, I wonder whether it might make sense to put this all in as a further
bunch of problems?

Totally happy to go with whatever you think is best!

Tim
