### ISSUE TITLE
Finite models of T(M,w)

### ISSUE THREAD

**Issue by rzach** [OpenLogicProject/OpenLogic#266]
The axioms of T(M,w) in the proof of undecidability of FOL include \forall x\forall y(x < y -> x \neq y). I don't think that's needed anywhere in the proof. If it isn't then T(M,w) should have a finite model whenever M halts on w. Verify this, and add an exercise (section?) to construct the finite model + explain why this shows that the decision problem for validity on all finite models is undecidable and possibly Trakhtenbrot's Theorem.

**Comment by PanuRaatikainen** [comment]
Hi Richard! 
I am not sure what is the status of this question. If it is a genuine question: Yes, you can prove Trakhtenbrot's Theorem in this way.  I worked it out in detail back in the 1990s as an essay for Jouko Väänänen's course on finite model theory. I think it is at least hinted here and there in the literature.
Best, Panu

**Comment by rzach** [comment]
I don't read Russian but according to the review in JSL https://doi.org/10.2307/2266840 Trakhtenbrot's original proof does not go this way.  However, the proofs in the standard finite model theory texts use the same idea. What's required is to add a whole bunch of stuff that ensures that any finite model reflects not just what the TM does but also what it doesn't do (e.g., rule out that Q_q_1(n,m) and Q_q_2(n,m) are both true).  That's maybe a bit too much for an exercise. For the regular undecidability proof we can drop both injectivity of ' *and* irreflexivity of < I think.

**Comment by rzach** [comment]
Hey @PanuRaatikainen I added a section on Trakhtenbrot's theorem -- maybe you are interested / want to help me out by checking if it's right? https://slc.openlogicproject.org/slc-screen.pdf

**Comment by PanuRaatikainen** [comment]
It seems all right to me, at least after my first reading. 
I can think about it more carefully in few days. 
If I can find my old detailed proof (I am afraid I have it only in a physical form, on paper, somewhere in my office) I could compare them carefully.  But I remember clearly that the basic idea was very similar.
Best, Panu

**Comment by rzach** [comment]
Thanks! One thing I'm a bit worried about is that the proof in Libkin's finite model theory has sentences that require that at any time, there's only one state active, one square read, and one symbol per square. I don't think that's needed but I have nagging doubts.

**Comment by PanuRaatikainen** [comment]
I don't think these are needed either.  As long as (finite or infinite) "time" is linearly ordered, it should go through, it seems to me. 
If the sentence only states that in the beginning, the initial configuration is such-and-such (with only one state etc.), and you follow the commands, you'll never end up having more than one state, symbol etc.  
To be sure, the sentence may have such unintended interpretations, and hence it may be tempting to rule them out, but I don't think that the proof requires that. 
The critical part apparently is that the sentence corresponding to a non-halting computation really does not have finite models: but it is enough that it does not halt in any finite time; whether in some unintended interpretations there are more than one state or symbol at one time etc. does not seem to matter.

**Comment by rzach** [comment]
Great, thanks so much for checking this!
