### ISSUE TITLE
Missing '!'

### ISSUE THREAD

**Issue by ogotchey** [OpenLogicProject/OpenLogic#304]
The most convenient way to report a typo should reference the file and line number where the typo occurs:

- Find the file in the content tree: https://github.com/OpenLogicProject/OpenLogic/tree/master/content
- Click on the line number; then on the menu indicated by three horizontal dots
- Select "Copy permalink" and paste that link below.

Alternatively describe the location of the typo (page #, "after Theorem 5.1", etc., and *mention which PDF you are referencing*)

Typo location: https://github.com/OpenLogicProject/OpenLogic/blob/0552395a1249a151c8b9ca41253019d125539525/content/first-order-logic/syntax-and-semantics/substitution.tex#L122

What is the typo: A(x) lacks a preceding '!' and thus actually renders as the English 'A' instead of the Greek phi.

Proposed correction: Change `$\lforall[x][A(x)]$` to `$\lforall[x][!A(x)]$` in line 122 of first-order-logic/syntax-and-semantics/substitution.tex

**Comment by rzach** [comment]
Thanks!
