### ISSUE TITLE
Typo in example 6 in sets-functions-relations/size-of-sets/enumerability.tex

### ISSUE THREAD

**Issue by furcyd** [OpenLogicProject/OpenLogic#316]
Typo location:

https://github.com/OpenLogicProject/OpenLogic/blob/87ad058e9cbc7e07b855d911cfca1013534a5335/content/sets-functions-relations/size-of-sets/enumerability.tex#L129

What is the typo:

g(n) as defined excludes 1 from the range

Proposed correction:

g(n) = 2n - 1

**Comment by rzach** [comment]
Good catch, yes. There is an alternate version of this (and two other) sections in this chapter that define enumerability differently, and use \Nat instead of \PosInt.  (The definition of g is correct if you are looking for functions Nat -> Nat.) You might like that better for your purposes.

**Comment by rzach** [comment]
PS see https://github.com/OpenLogicProject/set-theory/blob/master/settheory.tex for how they are imported in the Set Theory book.

**Comment by furcyd** [comment]
> PS see https://github.com/OpenLogicProject/set-theory/blob/master/settheory.tex for how they are imported in the Set Theory book.

Thanks!

**Comment by rzach** [comment]
Fixed in 514bad7913cbf6d1e3bad0372a6c1f5f427f9064
