### ISSUE TITLE
'Monotony' versus 'monotonicity'

### ISSUE THREAD

**Issue by beastaugh** [OpenLogicProject/OpenLogic#319]
The book (mostly) uses the term 'monotony' rather than  'monotonicity'. To be honest, I've never encountered the former used as a synonym for the latter in mathematical contexts, although that may be my ignorance speaking more than anything. But since 'monotonicity' seems to be far more widely used, I suggest that we switch wholesale to the latter. I'm happy to author a commit making this change.

**Comment by rzach** [comment]
Done in 8f2df193ebc5d18ce24dbea8a2658f3042e80399 thanks!
