### ISSUE TITLE
A typo in the "method" chapter

### ISSUE THREAD

**Issue by Heein-Park** [OpenLogicProject/OpenLogic#336]
The most convenient way to report a typo should reference the file and line number where the typo occurs:

- Find the file in the content tree: https://github.com/OpenLogicProject/OpenLogic/tree/master/content
- Click on the line number; then on the menu indicated by three horizontal dots
- Select "Copy permalink" and paste that link below.

Alternatively describe the location of the typo (page #, "after Theorem 5.1", etc., and *mention which PDF you are referencing*)

Typo location: https://github.com/OpenLogicProject/OpenLogic/blob/5df41c789b7ef9463b7c2061330c3b8cec7355c4/content/methods/proofs/cant-do-it.tex#L27

What is the typo:
"Others in the class may also struggle---but **_the_** may struggle with different things."

Proposed correction:
The word 'the' is mistyped as it may be 'they' corresponding with 'Others' in a preceding clause.
"Others in the class may also struggle---but _**they**_ may struggle with different things."

**Comment by rzach** [comment]
Was fixed in https://github.com/OpenLogicProject/OpenLogic/commit/6d9901c59529dcc1a18ba2e1bc5e7434e9c997d0
Thanks!
