### ISSUE TITLE
Theorem 7.13 references phi_i without ever defining i.

### ISSUE THREAD

**Issue by edwin2525** [OpenLogicProject/OpenLogic#340]
The most convenient way to report a typo should reference the file and line number where the typo occurs:

- Find the file in the content tree: https://github.com/OpenLogicProject/OpenLogic/tree/master/content
- Click on the line number; then on the menu indicated by three horizontal dots
- Select "Copy permalink" and paste that link below.

Alternatively describe the location of the typo (page #, "after Theorem 5.1", etc., and *mention which PDF you are referencing*)

Typo location:
https://github.com/OpenLogicProject/OpenLogic/blob/82a31811a017a839d6415b3f45556eaeeb336cdd/content/first-order-logic/syntax-and-semantics/formation-sequences.tex#L186

What is the typo:
Textbook uses "phi_i" without ever defining "i".

Proposed correction:
Maybe you meant n or meant to define i.

**Comment by rzach** [comment]
Thanks!
