### ISSUE TITLE
Frege

### ISSUE THREAD

**Issue by rikiheck** [OpenLogicProject/OpenLogic#342]
I was just looking through the book and stumbled across the Appendix on Basic Law V in 61.6 of the full build.
This is not accurate. Frege does not define extensions of concepts at all but rather the 'value-ranges' of functions. For the purposes of this book, it's entirely reasonable to abstract from this, but some kind of note should be added that this is what's being done. 
Alternatively, one could make the discussion more accurate. If you want to do that, I could have a go at re-writing the section.
Cheers,
Richard Kimberly Heck

**Comment by rzach** [comment]
This part is from @timbutton -- Tim, what do you think?

**Comment by timbutton** [comment]
If Heck wants to write a better version, great!
(Yup: I wrote it in a hurry; it’s inaccurate; I didn’t think it mattered too much, but I’d rather it were more accurate!)

—
Tim Button (he)
Head of Department, Philosophy, UCL
http://nottub.com/

**Comment by rikiheck** [comment]
I think it's adequate to add a clarifying footnote, and maybe a reference to an explanation elsewhere. You probably don't want to get into these particular weeds right here. Patch attached. Feel free to remove the citation if you think that's overkill.

[0001-Add-note-on-value-ranges.patch.txt](https://github.com/OpenLogicProject/OpenLogic/files/12850743/0001-Add-note-on-value-ranges.patch.txt)

**Comment by rzach** [comment]
Thanks again; sorry this took so long.
