### ISSUE TITLE
Definition 1.1 (Extensionality). If A and B are sets, then A = B iff every element of A is also an element of B, and vice versa.

### ISSUE THREAD

**Issue by aaronstevenson408** [OpenLogicProject/OpenLogic#343]
The most convenient way to report a typo should reference the file and line number where the typo occurs:

- Find the file in the content tree: https://github.com/OpenLogicProject/OpenLogic/tree/master/content
- Click on the line number; then on the menu indicated by three horizontal dots
- Select "Copy permalink" and paste that link below.

Alternatively describe the location of the typo (page #, "after Theorem 5.1", etc., and *mention which PDF you are referencing*)

Typo location: https://github.com/OpenLogicProject/OpenLogic/blob/d4e99d08a596c627e4f3a922b94dd74f0932b1cb/content/sets-functions-relations/sets/basics.tex#L27

What is the typo: iff

Proposed correction: if

**Comment by rzach** [comment]
Not a typo. Short for if and only if.

**Comment by aaronstevenson408** [comment]
Misunderstood , thanks for the clearup
