### ISSUE TITLE
Missing parenthesis on pg. 112

### ISSUE THREAD

**Issue by marethyu** [OpenLogicProject/OpenLogic#356]
The most convenient way to report a typo should reference the file and line number where the typo occurs:

- Find the file in the content tree: https://github.com/OpenLogicProject/OpenLogic/tree/master/content
- Click on the line number; then on the menu indicated by three horizontal dots
- Select "Copy permalink" and paste that link below.

Alternatively describe the location of the typo (page #, "after Theorem 5.1", etc., and *mention which PDF you are referencing*)

Typo location: pg. 112

What is the typo: Missing right parenthesis in the first line:

![capture1](https://github.com/OpenLogicProject/OpenLogic/assets/42195546/18d6bb23-3a79-4f68-9ae4-bca443707a4f)

Proposed correction:

**Comment by rzach** [comment]
Thanks!
