### ISSUE TITLE
Typo in Lindenbaum's lemma proof

### ISSUE THREAD

**Issue by marethyu** [OpenLogicProject/OpenLogic#364]
The most convenient way to report a typo should reference the file and line number where the typo occurs:

- Find the file in the content tree: https://github.com/OpenLogicProject/OpenLogic/tree/master/content
- Click on the line number; then on the menu indicated by three horizontal dots
- Select "Copy permalink" and paste that link below.

Alternatively describe the location of the typo (page #, "after Theorem 5.1", etc., and *mention which PDF you are referencing*)

Typo location:

pg. 232

What is the typo:

In the last sentence of the third paragraph in the proof of Lindenbaum's lemma, I believe `\subseteq\Gamma_{n+1}` should be `\Gamma_i\subseteq\Gamma_{n+1}`.

**Comment by rzach** [comment]
Thanks!
