### ISSUE TITLE
Minor error in example 12.25

### ISSUE THREAD

**Issue by marethyu** [OpenLogicProject/OpenLogic#367]
If I'm not mistaken, $\mathcal{Q}'\models\Gamma\cup\Delta_0$ should be $\mathcal{Q}'\models\Gamma_0\cup\Delta_0$ for some finite $\Gamma_0\subseteq\Gamma$, since $\Gamma$ could be infinite?

Also, `\{0<c\}` should be `\{\Obj{0}<c\}`.

![capture1](https://github.com/OpenLogicProject/OpenLogic/assets/42195546/cefe3dbb-3686-4727-ab92-7d2de3d16b23)

**Comment by beastaugh** [comment]
I see this is fixed, but I'm not convinced this was ever actually a typo: the family of structures that interpret $c$ as $1/K$ for $K \geq 1$ do satisfy all of $\Gamma$, not just some finite $\Gamma_0 \subseteq \Gamma$, and hence satisfy $\Gamma_0$ by monotonicity (realising this is part of the exercise of "prove this in detail"). But perhaps presenting it in the updated way makes it easier to understand…
