### ISSUE TITLE
Move content to content/

### ISSUE THREAD

**Issue by rzach** [OpenLogicProject/OpenLogic#58]
The main directory is getting cluttered. Proposal: move all the "parts" directories into a subdirectory content/. Requires changes to some \olimport commands in driver files depending on where to content is (eg changing 

\olimport*[sets-functions-relations]{sets-functions-relations}

to 

\olimport*[content/sets-functions-relations]{sets-functions-relations}

**Comment by GillRussell** [comment]
No objections here.

**Comment by nicolewyatt** [comment]
Nor from me. — N

--
Nicole Wyatt
Head, Department of Philosophy
University of Calgary

+1-403-220-3166
nicole.wyatt@ucalgary.ca

**Comment by rzach** [comment]
Fixed by commit 739a8f0e91bf947be2a6160cc4702d53c48d6ac6
