### ISSUE TITLE
Part on "Proof Methods"

### ISSUE THREAD

**Issue by rzach** [OpenLogicProject/OpenLogic#60]
We need a part that covers methods of proof, including inductive definitions and inductive proofs.

**Comment by rzach** [comment]
In progress: see "methods" branch.

**Comment by rzach** [comment]
One issue: https://github.com/OpenLogicProject/OpenLogic/blob/master/content/sets-functions-relations/sets/proofs-about-sets.tex is a very short intro on how to prove things about sets. A whole chapter on proving things about sets supercedes this. Take it out? Make it shorter with a reference to the chapter? Leave it in (but don't include it in Sets, Logic, Computation)?

**Comment by rzach** [comment]
Started a branch proofs, see https://github.com/OpenLogicProject/OpenLogic/commit/bb92fa3e3e0e755a08973a1d61670a9eab1fd32a

**Comment by rzach** [comment]
Needs: proving from existence claims, indirect proof, and what to leave out when writing it down, what to interpolate when reading a proof. Also, exercises. And deciding what to do with the one section in SFR/sets that deals with proofs about sets.

**Comment by nicolewyatt** [comment]
Would it be possible to remove [https://github.com/OpenLogicProject/OpenLogic/blob/master/content/sets-functions-relations/sets/proofs-about-sets.tex ](url) from the sets-functions-relations default once the chapter on proving things about sets is complete, but maybe keep it somewhere as an option, for people who don't want the whole chapter on proofs?

**Comment by rzach** [comment]
Yes, re: "deciding what to do with the one section in SFR/sets that deals with proofs about sets." 
1. We leave the section in the main text but remove it from SLC as is.
2. We shorten it and keep it as an example in the main text, including in SLC.
3. We move it to the methods/proofs chapter as a third example.

**Comment by rzach** [comment]
Ok, this is now reasonably complete:
http://people.ucalgary.ca/~rzach/static/open-logic/branches/proofs/open-logic-complete.pdf#chapter.29
Do we need (more) examples?  Exercises? 
And, what do we do about the proofs-about-sets section?

**Comment by rzach** [comment]
Done (https://github.com/OpenLogicProject/OpenLogic/commit/49e50f36a8bded8998c2f1cd6b1a3daa21580670)

Samara proofread it. I removed the proofs-about-sets section from the chapter but left the file in place. I used the material for the reading-proofs section.
