### ISSUE TITLE
Part on "Second-order Logic"

### ISSUE THREAD

**Issue by rzach** [OpenLogicProject/OpenLogic#63]
We should have a part on second-order logic, possibly together with discussion of type theory and plural logic.

**Comment by flapperleenie** [comment]
Should that be an expanded chapter ("Beyond First-order Logic") or a new part completely? 
I could perhaps write something on plural logic.

**Comment by rzach** [comment]
A completely new part, on the same level as "First-order Logic."

**Comment by rzach** [comment]
Fix in commit 7db17b4d4bc715a1d65d42727bdaa90dc3f02981
