### ISSUE TITLE
Add introduction to "First-order Logic" part

### ISSUE THREAD

**Issue by rzach** [OpenLogicProject/OpenLogic#69]
First-order logic gets right to it with formal definitions of languages, terms, formulas. Write an introductory chapter.

**Comment by GillRussell** [comment]
Hard part about that will be writing an introductory chapter that doesn't introduce a lot of really bad philosophy of logic.  (Not that you would do that, but lots of textbooks do.)

**Comment by rzach** [comment]
Maybe you would like to write it then? Just to be sure, you know?

**Comment by GillRussell** [comment]
I'd love to, but the introduction is really important - it's the first (and sometimes the only) part many people will read.  Maybe I could write an outline and run it past you, and you could tell me whether it's the kind of thing you want?

**Comment by rzach** [comment]
Yeah, you can just keep the discussion here on GitHub.  Someone doesn't 
like what you write, they can write their own introduction, right?

**Comment by GillRussell** [comment]
OK!

**Comment by rzach** [comment]
I wrote no an intro chapter but an intro section to the syntax-and-semantics part; see commit f905776.

I don't know if that's enough. I hope I didn't " introduce a lot of really bad philosophy of logic."

**Comment by rzach** [comment]
@GillRussell should I close this or do you want it open for a longer chapter still to be written by you?

**Comment by nicolewyatt** [comment]
I think a longer intro chapter would still be desirable.  @GillRussell if you have time to put together an outline perhaps we could still aim for one, but not for this fall?

**Comment by rzach** [comment]
This is now done, it's chapter 5 in https://slc.openlogicproject.org/
Do either of you want to read this and provide feedback in the next little while? If not, I'll close this and you can send me a new issue when you get around to it. @nicolewyatt @GillRussell
