### ISSUE TITLE
Separate propositional logic and first-order logic

### ISSUE THREAD

**Issue by rzach** [OpenLogicProject/OpenLogic#77]
Currently the "book" goes right into first-order logic.  People might want to start with propositional logic, especially if it's for a course that continues wih propositional logic only (say, modal, intuitionistic logic).  So we should separate out the propositional from the first order (quantifiers, identity) material in the chapters on proof systems so they can be included in a part on propositional logic (to be written/expanded: a first draft is in the axiomatic-deduction branch https://github.com/OpenLogicProject/OpenLogic/tree/axiomatic-deduction )

**Comment by nicolewyatt** [comment]
I see the appeal of having propositional logic separate in the cases you mention, but for those classes that are doing the whole thing, having it separate is pedagogically unsatisfying. Is there any way we could keep both options, or is the tagging just too hard?


On December 10, 2015 at 7:41:24 AM, Richard Zach (notifications@github.com<mailto:notifications@github.com>) wrote:

Currently the "book" goes right into first-order logic. People might want to start with propositional logic, especially if it's for a course that continues wih propositional logic only (say, modal, intuitionistic logic). So we should separate out the propositional from the first order (quantifiers, identity) material in the chapters on proof systems so they can be included in a part on propositional logic (to be written/expanded: a first draft is in the axiomatic-deduction branch https://github.com/OpenLogicProject/OpenLogic/tree/axiomatic-deduction )

**Comment by Cubesoup** [comment]
I would like to point out that a further advantage of separating the topics
is the Cartesian closed category / simply typed lambda calculus connection
to (intuitionistic) propositional logic, which the quantifiers make much
more confusing.

**Comment by rzach** [comment]
I'm planning to separate & tag.  -R

On 2015-12-15 03:56 PM, Nicole Wyatt wrote:
> I see the appeal of having propositional logic separate in the cases 
> you mention, but for those classes that are doing the whole thing, 
> having it separate is pedagogically unsatisfying. Is there any way we 
> could keep both options, or is the tagging just too hard?
>
>
> On December 10, 2015 at 7:41:24 AM, Richard Zach 
> (notifications@github.com<mailto:notifications@github.com>) wrote:
>
> Currently the "book" goes right into first-order logic. People might 
> want to start with propositional logic, especially if it's for a 
> course that continues wih propositional logic only (say, modal, 
> intuitionistic logic). So we should separate out the propositional 
> from the first order (quantifiers, identity) material in the chapters 
> on proof systems so they can be included in a part on propositional 
> logic (to be written/expanded: a first draft is in the 
> axiomatic-deduction branch 
> https://github.com/OpenLogicProject/OpenLogic/tree/axiomatic-deduction )
>
> —
> Reply to this email directly or view it on 
> GitHub<https://github.com/OpenLogicProject/OpenLogic/issues/77>.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/OpenLogicProject/OpenLogic/issues/77#issuecomment-164916932>.
>

-- 
Richard Zach ...... http://www.ucalgary.ca/rzach/
Professor,             Department  of  Philosophy
University of Calgary, Calgary AB T2N 1N4, Canada

**Comment by rzach** [comment]
Ok, I've done this. It's not very intrusive, basically just separating things into more sections. Material can now be (I think) reused without quantifier easily. Exception: the soundness proof. I'll leave that for another day.
